# Generated by Django 2.1 on 2020-05-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190225_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complent',
            name='proof',
            field=models.FileField(upload_to='media/proof'),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='img',
            field=models.ImageField(upload_to='media/criminal/Image'),
        ),
    ]
