# Generated by Django 2.1.4 on 2021-01-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200514_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complent',
            name='proof',
            field=models.FileField(upload_to='media/'),
        ),
    ]
